language: php

os: linux

php:
  - 7.1
  - 7.2
  - 7.3

env:
  - LARAVEL_VERSION=^5.8
  - LARAVEL_VERSION=^6.0

jobs:
  fast_finish: true
  exclude:
    - php: 7.1
      env: LARAVEL_VERSION=^6.0

before_install:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source
  - if [ "$LARAVEL_VERSION" !== "" ]; then composer require --dev "laravel/laravel:${LARAVEL_VERSION}" --no-update; fi;
  - composer update

script:
  - composer test
